execute_sudo: Fix when SUDO_ASKPASS without sudo
Homebrew/install pull request #358
Opened 2020-11-26 18:45 UTC by sjackman

Fix a bug when `SUDO_ASKPASS` is defined but `have_sudo_access` is false.

2020-11-26 18:45 UTC, sjackman commented
cc @hwalinga @andreineculau

2020-11-26 19:48 UTC, MikeMcQuaid requested changes
Would love to see https://github.com/Homebrew/install/pull/357 land before we make any other changes here.

2020-11-26 19:55 UTC, andreineculau approved these changes

2020-11-26 21:13 UTC, hwalinga commented
You don't want to simplify with ?

```sh
if ..
   sudo -A args
else 
   sudo args
fi
```

2020-11-27 04:28 UTC, sjackman commented
> You don't want to simplify with ?

I wrote that up first, and then decided that I like this better. 🤷‍♂️

2020-11-27 04:31 UTC, sjackman commented
Sure. Blocked on PR https://github.com/Homebrew/install/pull/357

2020-11-27 16:02 UTC, MikeMcQuaid commented
https://github.com/Homebrew/install/pull/357 has been merged so I think this can land whenever!

2020-11-27 16:02 UTC, MikeMcQuaid approved these changes

2020-11-27 22:00 UTC, merged